Workiva/dependency_validator

pubspec.yaml

* [WP-5430 Add special message when depending on the analyzer package but not us…](https://github.com/Workiva/dependency_validator/pull/7)
* [UIP-3024 Fix not properly ignoring "missing packages"](https://github.com/Workiva/dependency_validator/pull/10)
* [UIP-3028 Add test for respecting ignored packages on missing dep lists](https://github.com/Workiva/dependency_validator/pull/12)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dependency_validator/compare/1.0.0...Workiva:release_dependency_validator_1_0_1
Diff Between Last Tag and New Tag: https://github.com/Workiva/dependency_validator/compare/1.0.0...1.0.1
The logs for the request that created this PR can be found …

UIP-2883 Release dependency_validator 1.0.1

---

README.md
bin/dependency_validator.dart
lib/dependency_validator.dart
test/executable_test.dart

We need the ability to not fail when there are missing developer dependencies. Because these don't affect the dependency tree for consumers it's not a big deal.
- Add flags for turning off failing for each validation check.
- Note: I only see the `--no-fatal-missing-dev` flag being used.
- Verify tests pass
Properly failing when it is expected to fail.
---
FYA: @greglittlefield-wf @toddbeckman-wf @maxwellpeterson-wf 
FYI: @evanweible-wf

WP-6077: Add flags to control when the executable fails

---

bin/dependency_validator.dart
lib/dependency_validator.dart
lib/src/utils.dart
pubspec.yaml
test/executable_test.dart

https://github.com/Workiva/dependency_validator/issues/8
- Add the `--exclude-dir` flag
- Verify tests pass
- Error reporting
---
FYA: @greglittlefield-wf @maxwellpeterson-wf @toddbeckman-wf 
FYI: @evanweible-wf

UIP-3068 Add ability to exclude directories when checking for infractions

---

lib/src/utils.dart
test/import_export_regex_test.dart

The regex that detected import/export statements didn't account for packages with numbers in their names.
This can cause false positives and false negatives when using dependnency_validator (I hit one of each when using it).
- Account for numbers in package names
- Add tests for package name regex, including regression tests for package names with numbers
- Boyscouting: update regex for two additional edge cases:
- Leading spaces
- Triple-quoted exports (apparently you can do that)
- imports/exports not separated by newlines
- This is definitely an edge case, so let me know if my changes to the regex to support this too severe
- Note: it looks like adjacent string concatenation is also allowed; supporting that is probably best left for another time (if at all), and best for a tool like …

UIP-3088 Fix detection of packages whose names contain numbers

---

pubspec.yaml

* [UIP-3088 Fix detection of packages whose names contain numbers](https://github.com/Workiva/dependency_validator/pull/17)
Requested by: @maxpeterson-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dependency_validator/compare/1.1.0...Workiva:release_dependency_validator_1_1_1
Diff Between Last Tag and New Tag: https://github.com/Workiva/dependency_validator/compare/1.1.0...1.1.1

UIP-3080 Release dependency_validator 1.1.1

---

bin/dependency_validator.dart

This executable has no usage documentation.
Add it.
```
? pub run dependency_validator -h 
-h, --[no-]help                    Displays this info.
--[no-]verbose                 Display extra information for debugging.
-i, --ignore                       Comma-delimited list of packages to ignore from validation.
-x, --exclude-dir                  Comma-delimited list of directories to exclude from validation.
--[no-]fatal-pins              Whether to fail on dependency pins.
(defaults to on)
--[no-]fatal-under-promoted    Whether to fail on dependencies that are in `dev_dependencies` that should be in `dependencies`.
(defaults to on)
--[no-]fatal-over-promoted     Whether to fail on dependencies that are in `dependencies` that should be in `dev_dependencies`.
(defaults to on) …
```

AF-137 add help option

---

CHANGELOG.md
pubspec.yaml

* [pins not ignoring packages](https://github.com/Workiva/dependency_validator/pull/37)
Requested by: @jayudey-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dependency_validator/compare/1.2.1...Workiva:release_dependency_validator_1_2_2
Diff Between Last Tag and New Tag: https://github.com/Workiva/dependency_validator/compare/1.2.1...1.2.2

AF-1887 Release dependency_validator 1.2.2

---

CHANGELOG.md
lib/dependency_validator.dart
test/executable_test.dart
test_fixtures/analyzer/pubspec.lock
test_fixtures/dependency_pins/pubspec.lock
test_fixtures/missing/pubspec.lock
test_fixtures/over_promoted/pubspec.lock
test_fixtures/under_promoted/pubspec.lock
test_fixtures/unused/pubspec.lock
test_fixtures/valid/pubspec.lock

The `--ignore` should allow consumers to exempt a known over-promoted dependency, but was not.
@corwinsheahan-wf @sebastianmalysa-wf @robbecker-wf 
fyi @travissanderson-wf

AF-3771 Fix bug with ignoring over-promoted deps

---

lib/src/utils.dart
test/utils_test.dart

When there is a min but not a max, dep validator fails:
https://ci.webfilings.com/build/1392171
Run this on that library with these changes.

AF-2011 should not throw when no max bound

---

pubspec.yaml

* [AF-2011 should not throw when no max bound](https://github.com/Workiva/dependency_validator/pull/40)
* [AF-3771 Fix bug with ignoring over-promoted deps](https://github.com/Workiva/dependency_validator/pull/44)
Requested by: @evan.weible
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dependency_validator/compare/1.2.3...Workiva:release_dependency_validator_1.2.4
Diff Between Last Tag and New Tag: https://github.com/Workiva/dependency_validator/compare/1.2.3...1.2.4

AF-2531 Release dependency_validator 1.2.4

---

pubspec.yaml

* [CPLAT-7378: Add build_vm_compilers to common binary packages.](https://github.com/Workiva/dependency_validator/pull/50)
Requested by: @todbachman-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dependency_validator/compare/1.3.0...Workiva:release_dependency_validator_1.4.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/dependency_validator/compare/1.3.0...1.4.0

RM-56288 Release dependency_validator 1.4.0

---

lib/src/constants.dart
test_fixtures/common_binaries/pubspec.yaml

When we use `workivaConfig` without customization `dart_dev` gets flagged by  `dependency_validator`.
`dart_dev` added to default ignore list

CPLAT-8095: Add `dart_dev` to commonBinaryPackages

---

CHANGELOG.md
lib/dependency_validator.dart
lib/src/utils.dart
pubspec.yaml
test/executable_test.dart
test/utils_test.dart
test_fixtures/valid/analysis_options.yaml
test_fixtures/valid/pubspec.yaml

Packages can include analysis options from another package in their own `analysis_options.yaml`. This PR adds support for detecting that usage so that it doesn't think that a package only depended on for that purpose is unused.

CPLAT-8601: Detect package use in analysis_options.yaml

---

lib/dependency_validator.dart
lib/src/constants.dart
lib/src/utils.dart
test/utils_test.dart

Take imports from .less file into account to produce more accurate dependency analysis
Read and analyze .less files for imports. Basically same as scss but different file extension and regex.
Support .less files analysis
Please review: @Workviva/app-frameworks

Validate less imports

---

bin/dependency_validator.dart
lib/dependency_validator.dart
lib/src/constants.dart
lib/src/utils.dart
pubspec.yaml
test/executable_test.dart
test/utils_test.dart

There are several popular packages that currently have to be ignored when running dependency_validator because they are only used for the builder they provide, which is something that gets applied automatically when running build_runner and not something we can detect via imports in the source code.
Look up the source for each dependency in ~/.pub-cache to see if a build.yaml exists, parse it, and see if any builders are defined. If a dependency defines builder(s), we should consider it "used".
[contributing-review-types]: …

CPLAT-11298 detect builders

---

lib/dependency_validator.dart

Allow dependency validator to run on windows. Expanding upon #69 
use path.fromUri when searching for executables.
Please review: @evanweible-wf 
Ran dependency_validator on both windows and mac, using the same project and got the same results.

Handle Windows paths when searching for executables

---

CHANGELOG.md
README.md
dart_dependency_validator.yaml
lib/src/dependency_validator.dart
lib/src/pubspec_config.dart
lib/src/utils.dart
pubspec.yaml
test/executable_test.dart

`pub publish` warns when it finds unrecognized keys, which is problematic because we currently read static config from a `dependency_validator` entry in `pubspec.yaml`.
- Deprecate the current static config location within `pubspec.yaml` (the executable now warns when it is used)
- Add support for reading the same config format (without the `dependency_validator:` key) from a `dart_dependency_validator.yaml` file in the root of the package. This name was chosen to match the convention set by the `test` package using a `dart_test.yaml` config file.
- Tests have been updated and both the deprecated and new config codepaths are verified.

CPLAT-13993: Read config from dart_dependency_validator.yaml if available

---

CHANGELOG.md
bin/dependency_validator.dart
lib/src/dependency_validator.dart
test/executable_test.dart

When non-recognized args are used, we print the help message, but still exit with a `0` exit code. This can cause false positives in CI if legacy command line args are used.
* Return appropriate exit code
* Add test

Exit with usage code when incorrect args are used

---

CHANGELOG.md
bin/dependency_validator.dart
lib/dependency_validator.dart
lib/src/constants.dart
lib/src/pubspec_config.dart
lib/src/pubspec_config.g.dart
lib/src/utils.dart
pubspec.yaml
test/executable_test.dart
test/utils_test.dart

Back patch of [this PR](https://github.com/Workiva/dependency_validator/pull/78) to the 2.x release line.
* Cherry pick changes from that ^ PR.
* Ran format under dart 2.14.4

2.0.2 return non zero for bad usage

---

skynet.yaml

Currently the skynet config is running on pull requests as well as releases which is causing us to hit the github api rate limit, we don't really need to have the skynet config running on pull requests because it's just needed for release pipelines. 
Add a run config to skynet that limits running to just releases and if there are changes to the skynet.yaml
Run skynet only on releases
[contributing-manual-testing]: …

FW-167 Only run skynet on releases

---

.github/workflows/dart_ci.yaml
Dockerfile
lib/src/pubspec_config.g.dart
pubspec.yaml

We want to get to analyzer 5 and prepare for Dart 3.
Update json_serializable to 6 and rebuild. Fix CI matrix to run on only supported Dart versions.

Update json_serializable to get to analyzer 5

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/dart_ci.yaml
README.md
lib/src/dependency_validator.dart
lib/src/import_export_ast_visitor.dart
pubspec.yaml
test/executable_test.dart

Includes changes from both:
- #107
- #108
Any current consumers of dependency_validator might encounter failures due to these changes, merging into a single v4 branch, and will be released as a major to specifically inform the "breaking" changes

FEA-3682: v4

---

pubspec.yaml

* Major changes:
* [FEA-3682: v4](https://github.com/Workiva/dependency_validator/pull/111)
* [FEDX-687 : GHA OSS changes to dependency_validator](https://github.com/Workiva/dependency_validator/pull/110)
Requested by: @matthewnitschke-wk
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dependency_validator/compare/3.2.3...Workiva:release_dependency_validator_4.0.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/dependency_validator/compare/3.2.3...4.0.0
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerR …

RM-215560 Release dependency_validator 4.0.0

---

CHANGELOG.md

Updated the changelog for the v4 release

v4 Changelog update

---

CHANGELOG.md
lib/src/dependency_validator.dart
test/executable_test.dart

One of the new checks within v4 included an invalid assumption: https://github.com/Workiva/dependency_validator/pull/107
This is simply not true, non-dev dependencies can exist within `bin`, I was mistaken on the original intent of #106 
Reverted the bad assumption
-

FEA-3685: Reverted non-dev bin import usage errors

---

CHANGELOG.md
lib/src/dependency_validator.dart
test/executable_test.dart

Reverts Workiva/dependency_validator#115
I was wrong, it was correctly implemented and completely thought I had implemented a different feature

Revert "FEA-3685: Reverted non-dev bin import usage errors"

---

.github/workflows/dart_ci.yaml
README.md

The best practice suggestion is to install dependency_validator globally, instead of including it within the pubspec.yaml as a dev_dependency
- Updated the readme to explain the best practice installation method, installing it globally
- Fixed gha bug where sbom was failing due to being ran twice

Fixed broken GHA and updated installation instructions

---

pubspec.yaml

I noticed analyzer was being resolved to a lower version than available, it's causing warnings in the build runner for freezed.
I opened the depended-on analyzer versions to include the 6.#.# major release, but less than 7.#.# (Not out yet anyway)
I have no idea the implications this may have, and have not looked around this code base. From my testing, everything is operating normally as far as I can see, but this would need a maintainer to run some tests to confirm. I checked the changes in the analyzer package version notes, they seem minimal and I'm guessing won't affect anything with this package :)

Update analyzer constraint

---

pubspec.yaml

* Minor changes:
* [Update analyzer constraint](https://github.com/Workiva/dependency_validator/pull/117)
* [v4 Changelog update](https://github.com/Workiva/dependency_validator/pull/114)
* [FEA-3685: Reverted non-dev bin import usage errors](https://github.com/Workiva/dependency_validator/pull/115)
* [Revert "FEA-3685: Reverted non-dev bin import usage errors"](https://github.com/Workiva/dependency_validator/pull/116)
* [Fixed broken GHA and updated installation instructions](https://github.com/Workiva/dependency_validator/pull/120)
* [Add dependabot.yml](https://github.com/Workiva/dependency_validator/pull/121)
* [GHA: Bump actions/checkout from 2 to 4 in the gha-dependencies group](https://github.com/Workiva/dependency_validator/pull/1 …

RM-256973 Release dependency_validator 4.1.0

---

CHANGELOG.md

Rosie went rogue and merge https://github.com/Workiva/dependency_validator/pull/123 before I could update the changelog
Updates the changelog to include the updates for v4.1.0, so we can get a successful pub publish
- CI passes

FEA-3927: Updated changelog for v4.1.0

---

.github/workflows/ci.yaml
lib/src/import_export_ast_visitor.dart

If dependency_validator is ran on a file which contains invalid dart syntax, it will fail without a very good message
Updates the output of the parse error, including the name of the file that could not be parsed

FEDX-1589: Include file path on parse error

---

.github/workflows/ci.yaml
CHANGELOG.md
pubspec.yaml

* [FEA-3927: Updated changelog for v4.1.0](https://github.com/Workiva/dependency_validator/pull/124)
* [fedx_codeowners_file](https://github.com/Workiva/dependency_validator/pull/126)
* [FEDX-1587: implemented gha-dart-oss](https://github.com/Workiva/dependency_validator/pull/127)
* [FEDX-1589: Include file path on parse error](https://github.com/Workiva/dependency_validator/pull/128)
Requested by: @matthewnitschke-wk
@Workiva/release-management-p
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dependency_validator/compare/4.1.0...Workiva:release_dependency_validator_4.1.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/dependency_validator/compare/4.1.0...4.1.1
The logs for the request that created …

RM-263537 Release dependency_validator 4.1.1

---

.github/workflows/ci.yaml
.github/workflows/publish.yaml
CHANGELOG.md
README.md
bin/dependency_validator.dart
example/example.md
lib/src/dependency_validator.dart
lib/src/pubspec_config.dart
lib/src/pubspec_config.g.dart
lib/src/utils.dart
pubspec.yaml
test/executable_test.dart
test/pubspec_to_json.dart
test/utils.dart
test/workspace_test.dart

Fixes #137 by supporting use in a mono-repo
In a regular package: nothing
In a sub-package of a workspace: nothing
In a workspace: instead of failing, recursively run itself on all sub-packages
I did remove the error condition that `dart pub get` must be run before running the tool, since that was throwing errors for workspaces, and I did not see a use for it (the `pubspec.lock` or `.dart_tool` files are never checked, only the code and `pubspec.yaml`).
Looking into adding unit tests now, but basically, [create a workspace](https://dart.dev/tools/pub/workspaces) and try running the tool in there. 
For now, I had to add a dependency override on pubspec_parse until https://github.com/dart-lang/tools/pull/1948 is merged. For some reason that's affecting the tests, so many of them are failing …

Support Pub Workspaces

---

pubspec.yaml

* Major changes:
* [Support Pub Workspaces](https://github.com/Workiva/dependency_validator/pull/138)
* [FEDX-2363: Reset the version of dependency_validator](https://github.com/Workiva/dependency_validator/pull/142)
Requested by: @matthewnitschke-wk
@Workiva/release-management-p
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dependency_validator/compare/4.1.2...Workiva:release_dependency_validator_5.0.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/dependency_validator/compare/4.1.2...5.0.0
This pull request can be recreated by clicking …

RM-302023 Release dependency_validator 5.0.0

---

CHANGELOG.md

Auto-merge of release PRs was implemented causing rosie to automatically merge the release PR before the changelog could be updated. This broke pub.dev publishing, but still bumped the tag
- Manually updates the changelog to include the documentation on the latest changes. Also, RMConsole has been updated to no longer auto-merge release PRs, as well as make `validate-publish` a required workflow (preventing this issue in the future)

Updated changelog to fix release

---

lib/src/dependency_validator.dart

Currently, the `ignore` field only applies to some rules in the dependency_validator execution process
If you're explicitly ignoring a dependency, it doesn't make sense that _some_ rules can still fail. As such, this PR changes the expectation of evaluation, where when `ignore` exists for a package, its full ignored from dep evaluation
> [!TIP]
> Note, this PR's base is `v4` and not `master`
>
> We need to backpatch the v4 version with this change, and this will be manually released once merged into v4. We will create a similar PR in master so the functionality between these branches doesn't change

FEDX-2722: Update the `ignore` field to ignore everything, not just specific checks

---

lib/src/dependency_validator.dart

We backpatched this pr: https://github.com/Workiva/dependency_validator/pull/148, to v4.1.3, and want to apply the same change to master to prevent functional regressions with the latest release
Applies the same `ignore` specification, where anything ignored, is fully ignored

FEDX-2723: correctly ignore unused deps
