.travis.yml
pubspec.yaml
smithy.yaml

@jacehensley-wf @Workiva/web-platform-pp

UIP-2879 Remove `publish_to` directive from pubspec.yaml

---

CHANGELOG.md
lib/dependency_validator.dart
test/executable_test.dart

Follow up to #10 
@Workiva/app-frameworks

UIP-3028 Add test for respecting ignored packages on missing dep lists

---

pubspec.yaml

* [WP-6077: Add flags to control when the executable fails](https://github.com/Workiva/dependency_validator/pull/14)
* [UIP-3068 Add ability to exclude directories when checking for infractions](https://github.com/Workiva/dependency_validator/pull/15)
Requested by: @jacehensley-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dependency_validator/compare/1.0.1...Workiva:release_dependency_validator_1_1_0
Diff Between Last Tag and New Tag: https://github.com/Workiva/dependency_validator/compare/1.0.1...1.1.0

UIP-3037 Release dependency_validator 1.1.0

---

.travis.yml
analysis_options.yaml
lib/dependency_validator.dart
lib/src/utils.dart
pubspec.yaml
test/import_export_regex_test.dart
tool/dev.dart

* Strong-mode
* All recommended lints and fixes
* Increased ranges on `args`, `coverage`, and `dartdoc` to include versions that are also Dart 2.0 and DDC compatible.
@Workiva/app-frameworks

UIP-3191 Dart 2.0 and DDC compatibility changes

---

pubspec.yaml

* [UIP-3191 Dart 2.0 and DDC compatibility changes](https://github.com/Workiva/dependency_validator/pull/23)
Requested by: @robbecker-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dependency_validator/compare/1.1.1...Workiva:release_dependency_validator_1_1_2
Diff Between Last Tag and New Tag: https://github.com/Workiva/dependency_validator/compare/1.1.1...1.1.2

UIP-3089 Release dependency_validator 1.1.2

---

pubspec.yaml

* [BUILDTOOLS-2329: Update Dockerfile to mirror smithy.yaml](https://github.com/Workiva/dependency_validator/pull/22)
* [AF-159 validate scss deps](https://github.com/Workiva/dependency_validator/pull/26)
* [AF-178 check for dep pins](https://github.com/Workiva/dependency_validator/pull/27)
* [AF-137 add help option](https://github.com/Workiva/dependency_validator/pull/28)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dependency_validator/compare/1.1.2...Workiva:release_dependency_validator_1_2_0
Diff Between Last Tag and New Tag: https://github.com/Workiva/dependency_validator/compare/1.1.2...1.2.0
The logs for the request that created this PR can be found …

AF-430 Release dependency_validator 1.2.0

---

pubspec.yaml

* [AF-1879 Dart 2 compatibility](https://github.com/Workiva/dependency_validator/pull/35)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dependency_validator/compare/1.2.0...Workiva:release_dependency_validator_1_2_1
Diff Between Last Tag and New Tag: https://github.com/Workiva/dependency_validator/compare/1.2.0...1.2.1

AF-431 Release dependency_validator 1.2.1

---

pubspec.yaml

* [CPLAT-3300: CP Code Review and PR Merging Team agreement update](https://github.com/Workiva/dependency_validator/pull/46)
* [CPLAT-6965 Automatically ignore common binary packages](https://github.com/Workiva/dependency_validator/pull/47)
Requested by: @todbachman-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dependency_validator/compare/1.2.4...Workiva:release_dependency_validator_1.3.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/dependency_validator/compare/1.2.4...1.3.0

CPLAT-3772 Release dependency_validator 1.3.0

---

test_fixtures/analyzer/pubspec.yaml
test_fixtures/common_binaries/pubspec.yaml
test_fixtures/dependency_pins/pubspec.yaml
test_fixtures/fake_project/pubspec.yaml
test_fixtures/missing/pubspec.yaml
test_fixtures/over_promoted/pubspec.yaml
test_fixtures/under_promoted/pubspec.yaml
test_fixtures/unused/pubspec.yaml
test_fixtures/valid/pubspec.yaml

We need to bump sdk range in test files.
Update sdk range in `test/**/pubspec.yaml` to be dart2-only

CPLAT-8617: bump sdk range in test files

---

Dockerfile

Update the Dockerfile to use the dart2 base image

Update to dart2 base image

---

CHANGELOG.md
lib/dependency_validator.dart
lib/src/constants.dart
lib/src/utils.dart
test/utils_test.dart

Changes from #58 with an additional commit to update the changelog.

CPLAT-10392: v1.5.0

---

CHANGELOG.md
README.md
lib/dependency_validator.dart
lib/src/pubspec_config.dart
lib/src/pubspec_config.g.dart

V2 is ready for a beta release so we can start testing it out in some real repos.
Update the Readme and Changelog.
---
We'll cut the beta release PR after this merges to the wip branch.

CPLAT-11904: Readme and Changelog updates for v2.

---

pubspec.yaml

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dependency_validator/compare/1.5.0...Workiva:release_dependency_validator_2.0.0-beta
Diff Between Last Tag and New Tag: https://github.com/Workiva/dependency_validator/compare/1.5.0...2.0.0-beta

Release dependency_validator 2.0.0-beta

---

CHANGELOG.md
lib/dependency_validator.dart

CPLAT-12867: Use pkg:path to handle file URIs

---

skynet.yaml

Currently release pipelines are failing because they require a skynet run in order to pass the testing phase of the pipeline. We would like to not have to manually check that the github workflow passed and override the pipeline so we need a way to automatically check that the workflow passed and tell the pipeline that all is good.
Add a skynet.yaml that checks the github workflow run and passes or fails the skynet run depending on the results.
Add skynet run to check that the github workflow run passes  
[contributing-review-types]: …

FW-146 Add skynet config that verifies that github workflow passes

---

pubspec.yaml

* [FW-146 Add skynet config that verifies that github workflow passes](https://github.com/Workiva/dependency_validator/pull/90)
* [FW-167 Only run skynet on releases](https://github.com/Workiva/dependency_validator/pull/91)
* [FEA-440 Ensure all dependencies are also null-safe](https://github.com/Workiva/dependency_validator/pull/92)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dependency_validator/compare/3.2.1...Workiva:release_dependency_validator_3.2.2
Diff Between Last Tag and New Tag: https://github.com/Workiva/dependency_validator/compare/3.2.1...3.2.2
The logs for the request that created this PR can be found [here](https://w-rmconsole.appspot.com/release/release_event/5160374 …

RM-146257 Release dependency_validator 3.2.2

---

pubspec.yaml

* [Update references to the previous team name](https://github.com/Workiva/dependency_validator/pull/95)
* [Update json_serializable to get to analyzer 5](https://github.com/Workiva/dependency_validator/pull/103)
Requested by: @robbecker-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dependency_validator/compare/3.2.2...Workiva:release_dependency_validator_3.2.3
Diff Between Last Tag and New Tag: https://github.com/Workiva/dependency_validator/compare/3.2.2...3.2.3
This pull request can be recreated by clicking …

RM-151756 Release dependency_validator 3.2.3

---

analysis_options.yaml

This PR bumps/adds workiva_analysis_options to v2. This is being done in an effort to adopt consistency in
`analysis_options.yaml` files across the codebase, and ensure all developers are using the most up to date
functionality that the dart analyzer can provide.
Failing CI will be evaluated by someone from FEDX and resolved. We will reach out when the pr is ready for review.
If you have any questions, concerns, or opinions, please reach out to #support-frontend-dx.
[_Created by Sourcegraph batch change `Workiva/workiva_analysis_options_v2`._](https://workiva.sourcegraphcloud.com/organizations/Workiva/batch-changes/workiva_analysis_options_v2)

Workiva Analysis Options v2

---

pubspec.yaml

* [Workiva Analysis Options v2](https://github.com/Workiva/dependency_validator/pull/131)
* [Bump Workiva/gha-dart-oss from 0.1.6 to 0.1.7 in the gha group](https://github.com/Workiva/dependency_validator/pull/133)
* [raise_min_dart_sdk_2_19](https://github.com/Workiva/dependency_validator/pull/135)
Requested by: @robbecker-wf
@Workiva/release-management-p
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dependency_validator/compare/4.1.1...Workiva:release_dependency_validator_4.1.2
Diff Between Last Tag and New Tag: https://github.com/Workiva/dependency_validator/compare/4.1.1...4.1.2
The logs for the request that created this PR can be found [here](https://w-rmconsole.appspot.com/release/release_event/5160374167404 …

RM-285950 Release dependency_validator 4.1.2

---

pubspec.yaml

* [Latest analyzer version](https://github.com/Workiva/dependency_validator/pull/144)
Requested by: @matthewnitschke-wk
@Workiva/release-management-p
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dependency_validator/compare/5.0.0...Workiva:release_dependency_validator_5.0.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/dependency_validator/compare/5.0.0...5.0.1
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/5160374167404544/?repo_name=Workiva%2Fdependency_validator&pull_number=145)

RM-307835 Release dependency_validator 5.0.1

---

CHANGELOG.md
pubspec.yaml

We need to update the changlog and version for the 4.1.3 release

Updated changelog for v4.1.3 release
